### ISSUE TITLE
[1.2] Bossbar Compass with DeathPosTracker can be frozen and duplicated whenever someone dies

### ISSUE THREAD

**Issue by deiphiz** [arboriginal/SimpleCompass#2]
![2020-02-29_10 52 40](https://user-images.githubusercontent.com/3817935/75600905-3ff6a100-5af0-11ea-87b4-552fb5c6340c.png)

**Details**
Upon death, the compass seem to fail to refresh completely, displaying it on a new bossbar, leaving the old one frozen. Disabling and re-enabling the compass won't remove the frozen bossbars. The only way to get rid of it is to log out and back in.

I was able to mitigate this by setting the `fix_uuid_delay` and `refresh_status` options to 0, but the biggest factor is the `update_compass` option. I used to have `update_compass` set to 10, but when I set it back to the default 100, it happened a lot less, provided that *the player's ping is below the `update_compass` option*. If the ping is too high, the bug pretty much happens 100% of the time.

I have confirmed this bug happens with SimpleCompass as the only plugin enabled on my test server. I have no other plugins that create or modify bossbars in my production server.

**Environment**
 - Java version 1.15.2
 - Paper 118
 - Plugin version 1.2
 - Plugin configuration: https://pastebin.com/kU6Qgkys
 - Error log: N/A

I should note that this has happened to me in both 1.14 and 1.15 PaperSpigot.

**Comment by arboriginal** [comment]
Yep I know it, I got it sometimes too with last version of Spigot / Paper...

I'm actually busy by life and other projects unfortunately and TBH I no more play / dev for Minecraft actually because of that. I told to a friend who use Mohist I'll try when I can to make it also working with 1.12, so when I'll find time for it I'll work on this bug in the same time.

But sorry about that too: I've decided to close all my plugins issue trackers because I'm bored of people not able to read guidelines and make me loose my time.

So, I close this issue & tracker and maybe I'll update a new version in the future, maybe not. For now I have more important in mind.

I wish you, your friends and family not be affected by Covid.
